### ISSUE TITLE
brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb

### ISSUE THREAD

**Issue by pandait** [tebelorg/Tump#2] opened 2020-10-29 10:38 UTC
Calling Non-checksummed download of openssl formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.

**Comment by gausam** [comment] 2020-11-23 10:20
Duplicate of https://github.com/tebelorg/Tump/issues/1

- Download the file with: `wget https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb`
- Run brew with the file downloaded: `brew install openssl.rb`

_Source: https://github.com/tebelorg/Tump/issues/1#issuecomment-701530062_

**Comment by alxvallejo** [comment] 2021-04-25 02:59
`Error: Failed to load cask: openssl.rb
Cask 'openssl' is unreadable: wrong constant name #<Class:0x00007faa1a9e3c18>
Warning: Treating openssl.rb as a formula.
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/manifests/1.0.2t
#=#=#
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "openssl_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/openssl/manifests/1.0.2t`

**Closed as completed** 2022-07-10 10:24 UTC
